# Site settings
title: Jatin Verma
description: "Jatin's Homepage"
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/jatin_photo.png'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Jatin Verma'
  email: jatin.verma.205@gmail.com
  # mastodon: tzuehlke@mstdn.social
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  jverma205
  linkedin_username:  /in/jverma205
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
